spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot_library_project
    username: postgres
    password: ****
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
    database: postgresql


# Open API
springdoc:
  swagger-ui:
    path: /swagger-ui.html
